services:
  app:
    image: simple-test-docker:${IMAGE_TAG:-latest}  # Use environment variable, default to latest
    # Remove the build section if you're building manually in the workflow
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"  # PORT comes from secrets
    restart: always
    environment:
      - NODE_ENV=production